version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb_demo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - '27037:27017'